pip scripts rewrite in progress: no remote test run by ssh no scp from worker to server

diff --git a/pipscripts/pip-server-control b/pipscripts/pip-server-control
--- a/pipscripts/pip-server-control
+++ b/pipscripts/pip-server-control
@@ -7,10 +7,10 @@ VERSION="0.0.6"
 VERBOSE=""
 LOGFILE=""
 
-if [ -f "/etc/s9s-cmon-test/project.conf" ]; then
-    source /etc/s9s-cmon-test/project.conf
+if [ -f "$MYDIR/load_config.sh" ]; then
+    source $MYDIR/load_config.sh
 else
-    echo "File '/etc/s9s-cmon-test/project.conf' was not found." >&2
+    echo "File $MYDIR/load_config.sh was not found." >&2
     exit 5
 fi
 
@@ -386,10 +386,10 @@ function wake_server()
         source "$config_file"
     fi
 
-    pip-say --beep "Controller is starting up ${hostname}."
+    printVerbose "Controller is starting up ${hostname}."
 
     if [ -n "$CONF_HOST_PDU" ]; then
-        pip-say "Powering on server $CONF_HOST_NAME through the power distribution unit."
+        printVerbose "Powering on server $CONF_HOST_NAME through the power distribution unit."
         for pdu in $(echo "$CONF_HOST_PDU" | tr ',' ' '); do
             printVerbose "Switching on PDU $pdu."
             pip-pdu-control --on $pdu
@@ -400,17 +400,17 @@ function wake_server()
 
     if [ -n "$CONF_HOST_ILOM" ]; then
         printVerbose "Will use ILOM of ${CONF_HOST_NAME}."
-        pip-say "Will use integrated lights out manager on ${CONF_HOST_NAME}."
+        printVerbose "Will use integrated lights out manager on ${CONF_HOST_NAME}."
 
         # ILOM needs time to start...
         sleep 20
-        pip-say "ILOM start on ${CONF_HOST_NAME} proceeds in 40 seconds"
+        printVerbose "ILOM start on ${CONF_HOST_NAME} proceeds in 40 seconds"
         
         sleep 20
-        pip-say "ILOM start on ${CONF_HOST_NAME} proceeds in 20 seconds"
+        printVerbose "ILOM start on ${CONF_HOST_NAME} proceeds in 20 seconds"
 
         sleep 20
-        pip-say "Calling ILOM to start ${CONF_HOST_NAME}."
+        printVerbose "Calling ILOM to start ${CONF_HOST_NAME}."
         printVerbose "Using ILOM to start ${CONF_HOST_NAME}."
         file="/tmp/ilom.expect"
 
@@ -435,19 +435,19 @@ EOF
         retcode=$?
 
         if [ "$retcode" -ne 0 ]; then
-            pip-say "ILOM request failed with error code $retcode, attempting to compensate."
+            printVerbose "ILOM request failed with error code $retcode, attempting to compensate."
             printWarning "output: $output"
             printWarning "The $file exited with error."
             sleep 30
             timeout 15 $file
 
             if [ $? -ne 0 ]; then
-                pip-say "The second ILOM request is failed, server is off-line."
+                printVerbose "The second ILOM request is failed, server is off-line."
             else
-                pip-say "The second ILOM request succeeded."
+                printVerbose "The second ILOM request succeeded."
             fi
         else
-            pip-say "ILOM request suceeded, server is booting."
+            printVerbose "ILOM request suceeded, server is booting."
         fi
 
         rm -f $file
@@ -455,12 +455,12 @@ EOF
         macAddress=$(mac_for_server "$hostName")
         if [ -z "$macAddress" ]; then
             printError "MAC address for $hostName was not found."
-            pip-say "MAC address for $hostName was not found."
+            printVerbose "MAC address for $hostName was not found."
             return 1
         fi
 
         printVerbose "Waking server ${hostName} on ${macAddress}."
-        pip-say "Sending wake on lan message to host ${hostName}."
+        printVerbose "Sending wake on lan message to host ${hostName}."
         wakeonlan "$macAddress" >/dev/null 2>/dev/null
     fi
 
@@ -475,7 +475,7 @@ function shut_down_server()
         return 1
     fi
 
-    pip-say --beep "Shutting down ${hostname}."
+    printVerbose "Shutting down ${hostname}."
     echo "Trying to shut down host ${hostname}."
     if [ -n "$OPTION_USER" ]; then
         ssh -o UserKnownHostsFile=/dev/null \
@@ -606,15 +606,6 @@ EOF
     fi
 }
 
-if [ -z "$PROJECT_DATA_ROOT" ]; then
-cat <<EOF
-Environment variable PROJECT_DATA_ROOT is empty. It is likely
-because project.conf file is not available or wrong. Please
-fix it. An example content can be found in project.conf.example.
-EOF
-    exit -1
-fi
-
 HOST_STAT_ROOT="$PROJECT_DATA_ROOT/servers"
 function download_current_data()
 {
@@ -631,6 +622,8 @@ function download_current_data()
         CONF_HOST_STANDARD=""
         CONF_HOST_MAC=""
         CONF_HOST_PROTECTED=""
+        CONF_HOST_DATA_ROOT=""
+        CONF_HOST_USER=""
 
         source "$config"
 
@@ -989,7 +982,7 @@ function print_host_list_brief()
 
 function wake_all()
 {
-    pip-say "Starting all servers."
+    printVerbose "Starting all servers."
         for server in \
             core2 core3 storage01 \
             host01 host02 host03 host04 host05 \
@@ -1003,7 +996,7 @@ function wake_all()
         sleep 1
         pip-pdu-control --on dell1955_pdu01,dell1955_pdu02
 
-    pip-say "Starting all servers finished."
+    printVerbose "Starting all servers finished."
 }
 
 if [ -n "$LIST_OPTION" ]; then
@@ -1026,7 +1019,7 @@ elif [ -n "$ALL_OPTION" ]; then
     if [ "$WAKE_OPTION" ]; then
         wake_all
     elif [ "$SHUT_DOWN_OPTION" ]; then
-        pip-say "Shutting down all servers."
+        printVerbose "Shutting down all servers."
         for server in \
             core2 core3 \
             host01 host02 host03 host04 host05 \
@@ -1036,7 +1029,7 @@ elif [ -n "$ALL_OPTION" ]; then
         do
             pip-server-control --shut-down $server
         done
-        pip-say "Shutting down all servers finished."
+        printVerbose "Shutting down all servers finished."
     fi
 elif [ -n "$SHUT_DOWN_OPTION" ]; then
     for hostname in $(echo "$ARGUMENTS" | tr ',' ' '); do 
diff --git a/pipscripts/pip-test-daemon b/pipscripts/pip-test-daemon
--- a/pipscripts/pip-test-daemon
+++ b/pipscripts/pip-test-daemon
@@ -4,7 +4,6 @@ MYNAME=$(basename $0)
 MYDIR=$(dirname $0)
 MYDIR=$(readlink -m "$MYDIR")
 VERSION="0.0.1"
-VERBOSE=""
 LOGFILE="/dev/null"
 
 OPTION_CONTINUOUS=""
@@ -16,9 +15,16 @@ LAST_HOST_NAME="-"
 LAST_USER_NAME="-"
 SUM_STARTED_TESTS=0
 
-cd $MYDIR
-source "./utilityfunctions.sh"
-[ -f "./htmlfunctions.sh" ] && source "./htmlfunctions.sh"
+if [ -f "$MYDIR/load_config.sh" ]; then
+    source $MYDIR/load_config.sh
+else
+    echo "File $MYDIR/load_config.sh was not found." >&2
+    exit 5
+fi
+
+
+#source "./utilityfunctions.sh"
+#[ -f "./htmlfunctions.sh" ] && source "./htmlfunctions.sh"
 
 #
 # Prints the help text and exits.
@@ -61,7 +67,6 @@ while true; do
 
         --verbose)
             shift
-            VERBOSE="true"
             VERBOSE_OPTION="--verbose"
             ;;
 
@@ -92,31 +97,6 @@ while true; do
     esac
 done
 
-function pull_on_testhost()
-{
-    local idle_server=$1
-
-    printVerbose "Install fresh pipscripts to ${idle_server} before starting testing."
-
-    pushd ${PROJECT_S9S_TESTORIGIN_DIR}
-    ./install.sh --server=${idle_server}
-    popd
-
-    #printVerbose "Pulling in ${idle_server}:${PROJECT_CC_TESTORIGIN_DIR}"
-
-    #ssh -o UserKnownHostsFile=/dev/null \
-    #    -o StrictHostKeyChecking=no \
-    #    -o LogLevel=quiet \
-    #    $idle_server -- "cd ${PROJECT_CC_TESTORIGIN_DIR} && git pull"
-
-    #printVerbose "Pulling in ${idle_server}:${PROJECT_S9S_TESTORIGIN_DIR}"
-
-    #ssh -o UserKnownHostsFile=/dev/null \
-    #    -o StrictHostKeyChecking=no \
-    #    -o LogLevel=quiet \
-    #    $idle_server -- "cd ${PROJECT_S9S_TESTORIGIN_DIR} && git pull"
-}
-
 #
 # Waits until it finds an idle server, then starts the given test on it.
 #
@@ -132,24 +112,24 @@ function start_test()
     local retcode
     local counter
 
-    printVerbose "Loading '$config_file'..."
+    echo "Loading '$config_file'..."
     source "$config_file"
     local gitcommit="$githash"
 
     # 
     # Getting the list of available servers.
     #
-    printVerbose "Getting idle test servers"
+    echo "Getting idle test servers"
 
     let counter=0
-    printVerbose "pip-server-control --list --idle"
+    echo "pip-server-control --list --idle"
     idle_server=$(pip-server-control --list --idle | head -n 1)
     if [ -z "$user" ]; then
         user="$USER"
     fi
 
     if [ "$idle_server" == "" ]; then
-        printVerbose "No idle test server available"
+        echo "No idle test server available"
         return 6
     fi
 
@@ -168,36 +148,33 @@ function start_test()
         option_s9s="--s9s"
     fi
 
-    pull_on_testhost $idle_server
-
     LAST_TEST_STARTED=$(date)
     LAST_TEST_NAME="$testname"
     LAST_HOST_NAME="$idle_server"
 
     let SUM_STARTED_TESTS+=1
 
-    printVerbose "pip-cmon-test "\
+    echo "pip-cmon-test "\
         "$VERBOSE_OPTION "\
         "$option_s9s "\
-        "--server=$idle_server "\
         "--test=$testname "\
         "--user=$user "\
         "--git-branch=$gitbranch"\
         "--git-commit=$gitcommit"
 
-    pip-cmon-test \
-        $VERBOSE_OPTION \
-        $option_s9s \
-        --server="$idle_server" \
-        --test="$testname" \
-        --user="$user" \
-        --git-branch="$gitbranch" \
-        --git-commit="$gitcommit" &
+    #nohup ?
+    #pip-cmon-test \
+    #    $VERBOSE_OPTION \
+    #    $option_s9s \
+    #    --test="$testname" \
+    #    --user="$user" \
+    #    --git-branch="$gitbranch" \
+    #    --git-commit="$gitcommit" &
 
     # It takes some time till the pip-cmon-test will be started
     # on the choosen host and sets the host status properly.
 
-    sleep 10
+    sleep 5
 
     rm -f "$config_file"
 }
@@ -237,14 +214,22 @@ function print_report()
 
 function pull_local_testorigin_source()
 {
-    pushd "${PROJECT_CC_TESTORIGIN_DIR}"
-    git reset --hard HEAD >/dev/null 2>/dev/null
-    git pull >/dev/null 2>/dev/null
-    popd
-    pushd "${PROJECT_S9S_TESTORIGIN_DIR}"
-    git reset --hard HEAD >/dev/null 2>/dev/null
-    git pull >/dev/null 2>/dev/null
-    popd
+    if [ "${PROJECT_AUTO_PULL_TESTORIGIN}" == "true" ]; then
+
+        echo "Pulling in ${idle_server}:${PROJECT_CC_TESTORIGIN_DIR}"
+
+        pushd "${PROJECT_CC_TESTORIGIN_DIR}"
+        git reset --hard HEAD >/dev/null 2>/dev/null
+        git pull >/dev/null 2>/dev/null
+        popd
+
+        echo "Pulling in ${idle_server}:${PROJECT_S9S_TESTORIGIN_DIR}"
+
+        pushd "${PROJECT_S9S_TESTORIGIN_DIR}"
+        git reset --hard HEAD >/dev/null 2>/dev/null
+        git pull >/dev/null 2>/dev/null
+        popd
+    fi
 }
 
 #
@@ -257,15 +242,14 @@ function process_scheduled_tests()
     local config_files=$(schedule_files)
 
     if [ -z "$config_files" ]; then
-        #printVerbose "No tests scheduled."
-        sleep 10
+        #echo "No tests scheduled."
         return 0
     fi
 
     pull_local_testorigin_source
 
     for config_file in $(schedule_files); do
-        printVerbose "*** config_file: $config_file"
+        echo "*** config_file: $config_file"
         if [ ! -f "$config_file" ]; then
             continue
         elif [ ! -x "$config_file" ]; then
@@ -283,6 +267,7 @@ function process_scheduled_tests()
 if [ "$OPTION_CONTINUOUS" ]; then
     while true; do
         process_scheduled_tests
+        sleep 10
     done
 else 
     process_scheduled_tests
