Script updates.

diff --git a/pipscripts/pip-server-control b/pipscripts/pip-server-control
--- a/pipscripts/pip-server-control
+++ b/pipscripts/pip-server-control
@@ -10,6 +10,13 @@ OPTION_DEVICE=""
 OPTION_PRINT_FILES=""
 OPTION_USER="pipas"
 
+if [ -f "$MYDIR/utilityfunctions.sh" ]; then
+    source $MYDIR/utilityfunctions.sh
+else
+    echo "File '$MYDIR/utilityfunctions.sh' was not found." >&2
+    exit 5
+fi
+
 SUM_SERVERS=0
 SUM_OFF_LINE_SERVERS=0
 SUM_TESTING_SERVERS=0
@@ -20,49 +27,6 @@ SUM_DISK=0
 SUM_CONTAINERS=0
 
 OPTION_STATE_FILTER=""
-
-TERM_ERASE_EOL="\033[K"
-TERM_HOME="\033[0;0H"
-TERM_NORMAL="\033[0;39m"
-TERM_BOLD="\033[1m"
-TERM_INVERSE="\033[7m"
-XTERM_COLOR_RED="\033[0;31m"
-XTERM_COLOR_GREEN="\033[0;32m"
-XTERM_COLOR_ORANGE="\033[0;33m"
-XTERM_COLOR_BLUE="\033[0;34m"
-XTERM_COLOR_PURPLE="\033[0;35m"
-XTERM_COLOR_CYAN="\033[0;36m"
-XTERM_COLOR_LIGHT_GRAY="\033[0;37m"
-XTERM_COLOR_DARK_GRAY="\033[1;30m"
-XTERM_COLOR_LIGHT_RED="\033[1;31m"
-XTERM_COLOR_LIGHT_GREEN="\033[1;32m"
-XTERM_COLOR_YELLOW="\033[1;33m"
-XTERM_COLOR_LIGHT_BLUE="\033[1;34m"
-XTERM_COLOR_LIGHT_PURPLE="\033[1;35m"
-XTERM_COLOR_LIGHT_CYAN="\033[1;36m"
-XTERM_COLOR_WHITE="\033[1;37m"
-
-OWNER_COLOR="$XTERM_COLOR_ORANGE"
-USER_COLOR="\033[1m\033[38;5;212m"
-EMAIL_COLOR="$XTERM_COLOR_PURPLE"
-PROJECT_COLOR="\033[1m\033[38;5;210m"
-TEST_COLOR="\033[2m\033[38;5;190m"
-HOST_COLOR="\033[1m\033[38;5;184m"
-INC_COLOR="\033[1m\033[36m"
-QUERY_COLOR="\033[1m\033[36m"
-COMMENT_COLOR="\033[1m\033[38;5;12m"
-IP_COLOR="\033[2m\033[38;5;201m"
-FILE_COLOR="\033[38;5;119m"
-GROUP_COLOR="\033[2m\033[38;5;7m"
-DEVICE_COLOR="\033[1m\033[38;5;203m"
-
-OK_COLOR="$XTERM_COLOR_GREEN"
-WARN_COLOR="$XTERM_COLOR_YELLOW"
-ERR_COLOR="$XTERM_COLOR_RED"
-NORM_COLOR="$XTERM_COLOR_BLUE"
-DATE_COLOR="\033[1m\033[38;5;215m"
-
-source "$MYDIR/utilityfunctions.sh"
 
 #
 # Prints the software version and exits.
