Script changes.

diff --git a/pipscripts/pip-monitor-system b/pipscripts/pip-monitor-system
--- a/pipscripts/pip-monitor-system
+++ b/pipscripts/pip-monitor-system
@@ -8,8 +8,13 @@ VERBOSE=""
 LOGFILE=""
 HOST=""
 SSH="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet"
-source $MYDIR/utilityfunctions.sh
 
+if [ -f "$MYDIR/utilityfunctions.sh" ]; then
+    source $MYDIR/utilityfunctions.sh
+else
+    echo "File '$MYDIR/utilityfunctions.sh' was not found." >&2
+    exit 5
+fi
 
 export LC_ALL=C
 
@@ -28,42 +33,6 @@ function printVersionAndExit()
 {
     echo "$MYNAME Version $VERSION on $(hostname)" >&2
     exit 0
-}
-
-#
-# $*: the error message
-#
-#
-# Prints an error message to the standard error. The text will not mixed up with
-# the data that is printed to the standard output.
-#
-function printError()
-{
-    local datestring=$(date "+%Y-%m-%d %H:%M:%S")
-
-    echo -e "$MYNAME($$) $*" >&2
-
-    if [ "$LOGFILE" ]; then
-        echo -e "$datestring ERROR $MYNAME($$) $*" >>"$LOGFILE"
-    fi
-}
-
-#
-# $*: the message
-#
-# Prints all the arguments but only if the program is in the verbose mode.
-#
-function printVerbose()
-{
-    local datestring=$(date "+%Y-%m-%d %H:%M:%S")
-
-    if [ "$VERBOSE" == "true" ]; then
-        echo -e "$MYNAME($$) $*" >&2
-    fi
-
-    if [ "$LOGFILE" ]; then
-        echo -e "$datestring DEBUG $MYNAME($$) $*" >>"$LOGFILE"
-    fi
 }
 
 function printHelpAndExit()
@@ -176,7 +145,7 @@ function get_disk_throughput()
     local read_kilo
     local write_kilo
 
-    printVerbose "lines: $lines"
+    #printVerbose "lines: $lines"
 
     write_kilo=$(\
         echo "$lines" | grep "Actual DISK WRITE" | tail -n 1 | \
@@ -264,10 +233,10 @@ if [ ! -f "$CONFIG_FILE" ]; then
 else
     printVerbose "Loading config file '$CONFIG_FILE'."
     source "$CONFIG_FILE"
-    printVerbose "    MQTT_SERVER=$MQTT_SERVER"
-    printVerbose "      MQTT_PORT=$MQTT_PORT"
-    printVerbose "      MQTT_USER=$MQTT_USER"
-    printVerbose "  MQTT_PASSWORD=$MQTT_PASSWORD"
+    #printVerbose "    MQTT_SERVER=$MQTT_SERVER"
+    #printVerbose "      MQTT_PORT=$MQTT_PORT"
+    #printVerbose "      MQTT_USER=$MQTT_USER"
+    #printVerbose "  MQTT_PASSWORD=$MQTT_PASSWORD"
 fi
 
 function check_install_mosquitto()
@@ -287,10 +256,9 @@ function local_resources_to_mqtt()
     local message=$(get_resources)
     local retcode
 
-    echo "------------------------------------"
-    echo "     mqtt: mqtt://$MQTT_SERVER:$MQTT_PORT"
-    echo "    topic: $topic"
-    echo "  message: $message"
+    printVerbose "     mqtt: mqtt://$MQTT_SERVER:$MQTT_PORT"
+    printVerbose "    topic: $topic"
+    printVerbose "  message: $message"
     mosquitto_pub \
         -u "$MQTT_USER" \
         -P "$MQTT_PASSWORD" \
diff --git a/pipscripts/pip-sensor b/pipscripts/pip-sensor
--- a/pipscripts/pip-sensor
+++ b/pipscripts/pip-sensor
@@ -11,6 +11,14 @@ PDU_SERVER=""
 PDU_OUTLETS="all"
 PDU_OPERATION="on"
 
+
+if [ -f "$MYDIR/utilityfunctions.sh" ]; then
+    source $MYDIR/utilityfunctions.sh
+else
+    echo "File '$MYDIR/utilityfunctions.sh' was not found." >&2
+    exit 5
+fi
+
 #
 # Prints the software version and exits.
 #
@@ -19,48 +27,13 @@ function printVersionAndExit()
     echo "$MYNAME Version $VERSION on $(hostname)" >&2
 }
 
-#
-# $*: the error message
-#
-# Prints an error message to the standard error. The text will not mixed up with
-# the data that is printed to the standard output.
-#
-function printError()
-{
-    local datestring=$(date "+%Y-%m-%d %H:%M:%S")
-
-    echo -e "ERROR $*" >&2
-
-    if [ "$LOGFILE" ]; then
-        echo -e "$datestring ERROR $MYNAME($$) $*" >>"$LOGFILE"
-    fi
-}
-
-#
-# $*: the message
-#
-# Prints all the arguments but only if the program is in the verbose mode.
-#
-function printVerbose()
-{
-    local datestring=$(date "+%Y-%m-%d %H:%M:%S")
-
-    if [ "$VERBOSE" == "true" ]; then
-        echo -e "DEBUG $*" >&2
-    fi
-
-    if [ "$LOGFILE" ]; then
-        echo -e "$datestring DEBUG $MYNAME($$) $*" >>"$LOGFILE"
-    fi
-}
-
 function printHelpAndExit()
 {
 cat <<EOF
 Usage:
   $MYNAME [OPTION]... DEVICE 
 
-  $MYNAME - Turns on and off pdu outlets.
+  $MYNAME - 
 
   -h, --help           Print this help and exit.
   -v, --version        Print version information and exit.
